name: PR Build (Tauri)

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  build:
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Add wasm32 target (Yew/Trunk)
        run: rustup target add wasm32-unknown-unknown

      - name: Install Trunk
        run: cargo install trunk

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev \
            librsvg2-dev patchelf

      - name: Build Tauri app
        id: tauri
        uses: tauri-apps/tauri-action@v0.4.5
        with:
          args: --ci

      - name: Upload artifacts
        if: ${{ steps.tauri.outputs.artifactPaths != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.platform }}
          path: ${{ steps.tauri.outputs.artifactPaths }}
