name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Runs on tags like v1.0.0, v1.2.3, etc.
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-tauri:
    permissions:
      contents: write # Needed to create the release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Trunk
        run: cargo install trunk

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      # The core Tauri build action
      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }} # The tag that triggered the workflow
          releaseName: 'App v__VERSION__' # __VERSION__ will be replaced by the version from tauri.conf.json
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
